---
hooks:
  post_merge:
    - /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan storage:link
    - /usr/local/bin/php artisan optimize
