---
deployment:
  tasks:
    - /bin/echo "Deployment started"
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - /bin/echo "Deployment finished"
